name: Scrapper
on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install Python
        run: echo Hello, world!

      - name: Run script
        run: python image_scrapper.py
