name: Scrapper
on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        
      - name: Run script
        run: |
          cd modules,
          python modules/image_scrapper.py
